# Generated by Django 5.1.2 on 2024-10-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
    ]
